// Individual
var tr_ind_1year_45_m = require('../sasMember/tr/Individual/tr_ind_1year_45_m.js');
var tr_ind_1year_45_s = require('../sasMember/tr/Individual/tr_ind_1year_45_s.js');
var tr_ind_1year_90_m  = require('../sasMember/tr/Individual/tr_ind_1year_90_m.js');
var tr_ind_1year_90_s  = require('../sasMember/tr/Individual/tr_ind_1year_90_s.js');
var tr_ind_1year_180_m = require('../sasMember/tr/Individual/tr_ind_1year_180_m.js');
var tr_ind_1year_180_s = require('../sasMember/tr/Individual/tr_ind_1year_180_s.js');
var tr_ind_1year_365_m = require('../sasMember/tr/Individual/tr_ind_1year_365_m.js');
var tr_ind_1year_365_s = require('../sasMember/tr/Individual/tr_ind_1year_365_s.js');
var tr_ind_2year_45_m  = require('../sasMember/tr/Individual/tr_ind_2year_45_m.js');
var tr_ind_2year_45_s  = require('../sasMember/tr/Individual/tr_ind_2year_45_s.js');
var tr_ind_2year_90_m  = require('../sasMember/tr/Individual/tr_ind_2year_90_m.js');
var tr_ind_2year_90_s  = require('../sasMember/tr/Individual/tr_ind_2year_90_s.js'); 
var tr_ind_2year_180_m = require('../sasMember/tr/Individual/tr_ind_2year_180_m.js');
var tr_ind_2year_180_s = require('../sasMember/tr/Individual/tr_ind_2year_180_s.js');
var tr_ind_2year_365_m = require('../sasMember/tr/Individual/tr_ind_2year_365_m.js');
var tr_ind_2year_365_s = require('../sasMember/tr/Individual/tr_ind_2year_365_s.js');
var tr_ind_3year_45_m  = require('../sasMember/tr/Individual/tr_ind_3year_45_m.js');
var tr_ind_3year_45_s  = require('../sasMember/tr/Individual/tr_ind_3year_45_s.js');
var tr_ind_3year_90_m  = require('../sasMember/tr/Individual/tr_ind_3year_90_m.js');
var tr_ind_3year_90_s  = require('../sasMember/tr/Individual/tr_ind_3year_90_s.js');
var tr_ind_3year_180_m = require('../sasMember/tr/Individual/tr_ind_3year_180_m.js');
var tr_ind_3year_180_s = require('../sasMember/tr/Individual/tr_ind_3year_180_s.js');
var tr_ind_3year_365_m = require('../sasMember/tr/Individual/tr_ind_3year_365_m.js');
var tr_ind_3year_365_s = require('../sasMember/tr/Individual/tr_ind_3year_365_s.js');
var tr_ind_4year_45_m  = require('../sasMember/tr/Individual/tr_ind_4year_45_m.js');
var tr_ind_4year_45_s  = require('../sasMember/tr/Individual/tr_ind_4year_45_s.js');
var tr_ind_4year_90_m  = require('../sasMember/tr/Individual/tr_ind_4year_90_m.js');
var tr_ind_4year_90_s  = require('../sasMember/tr/Individual/tr_ind_4year_90_s.js');
var tr_ind_4year_180_m = require('../sasMember/tr/Individual/tr_ind_4year_180_m.js');
var tr_ind_4year_180_s = require('../sasMember/tr/Individual/tr_ind_4year_180_s.js');
var tr_ind_4year_365_m = require('../sasMember/tr/Individual/tr_ind_4year_365_m.js');
var tr_ind_4year_365_s = require('../sasMember/tr/Individual/tr_ind_4year_365_s.js');
var tr_ind_5year_45_m  = require('../sasMember/tr/Individual/tr_ind_5year_45_m.js');
var tr_ind_5year_45_s  = require('../sasMember/tr/Individual/tr_ind_5year_45_s.js');
var tr_ind_5year_90_m  = require('../sasMember/tr/Individual/tr_ind_5year_90_m.js');
var tr_ind_5year_90_s  = require('../sasMember/tr/Individual/tr_ind_5year_90_s.js');
var tr_ind_5year_180_m = require('../sasMember/tr/Individual/tr_ind_5year_180_m.js');
var tr_ind_5year_180_s = require('../sasMember/tr/Individual/tr_ind_5year_180_s.js');
var tr_ind_5year_365_m = require('../sasMember/tr/Individual/tr_ind_5year_365_m.js');
var tr_ind_5year_365_s = require('../sasMember/tr/Individual/tr_ind_5year_365_s.js');

// Family
var tr_f_1year_45_m  = require('../sasMember/tr/Family/tr_f_1year_45_m.js');
var tr_f_1year_45_s  =   require('../sasMember/tr/Family/tr_f_1year_45_s.js');
var tr_f_1year_90_m  =  require('../sasMember/tr/Family/tr_f_1year_90_m.js');
var tr_f_1year_90_s  =  require('../sasMember/tr/Family/tr_f_1year_90_s.js');
var tr_f_1year_180_m =  require('../sasMember/tr/Family/tr_f_1year_180_m.js');
var tr_f_1year_45_s  =   require('../sasMember/tr/Family/tr_f_1year_45_s.js');
var tr_f_1year_180_s =  require('../sasMember/tr/Family/tr_f_1year_180_s.js');
var tr_f_1year_365_m =  require('../sasMember/tr/Family/tr_f_1year_365_m.js');
var tr_f_1year_365_s =  require('../sasMember/tr/Family/tr_f_1year_365_s.js');
var tr_f_2year_45_m  =  require('../sasMember/tr/Family/tr_f_2year_45_m.js');
var tr_f_2year_45_s  =  require('../sasMember/tr/Family/tr_f_2year_45_s.js');
var tr_f_2year_90_m  =  require('../sasMember/tr/Family/tr_f_2year_90_m.js');
var tr_f_2year_90_s  =  require('../sasMember/tr/Family/tr_f_2year_90_s.js'); 
var tr_f_2year_180_m =  require('../sasMember/tr/Family/tr_f_2year_180_m.js');
var tr_f_2year_180_s =  require('../sasMember/tr/Family/tr_f_2year_180_s.js');
var tr_f_2year_365_m =  require('../sasMember/tr/Family/tr_f_2year_365_m.js');
var tr_f_2year_365_s =  require('../sasMember/tr/Family/tr_f_2year_365_s.js');
var tr_f_3year_45_m  =  require('../sasMember/tr/Family/tr_f_3year_45_m.js');
var tr_f_3year_45_s  =  require('../sasMember/tr/Family/tr_f_3year_45_s.js');
var tr_f_3year_90_m  =  require('../sasMember/tr/Family/tr_f_3year_90_m.js');
var tr_f_3year_90_s  =  require('../sasMember/tr/Family/tr_f_3year_90_s.js');
var tr_f_3year_180_m =  require('../sasMember/tr/Family/tr_f_3year_180_m.js');
var tr_f_3year_180_s =  require('../sasMember/tr/Family/tr_f_3year_180_s.js');
var tr_f_3year_365_m =  require('../sasMember/tr/Family/tr_f_3year_365_m.js');
var tr_f_3year_365_s =  require('../sasMember/tr/Family/tr_f_3year_365_s.js');
var tr_f_4year_45_m  =  require('../sasMember/tr/Family/tr_f_4year_45_m.js');
var tr_f_4year_45_s  =  require('../sasMember/tr/Family/tr_f_4year_45_s.js');
var tr_f_4year_90_m  =  require('../sasMember/tr/Family/tr_f_4year_90_m.js');
var tr_f_4year_90_s  =  require('../sasMember/tr/Family/tr_f_4year_90_s.js');
var tr_f_4year_180_m =  require('../sasMember/tr/Family/tr_f_4year_180_m.js');
var tr_f_4year_180_s =  require('../sasMember/tr/Family/tr_f_4year_180_s.js');
var tr_f_4year_365_m =  require('../sasMember/tr/Family/tr_f_4year_365_m.js');
var tr_f_4year_365_s =  require('../sasMember/tr/Family/tr_f_4year_365_s.js');
var tr_f_5year_45_m  =  require('../sasMember/tr/Family/tr_f_5year_45_m.js');
var tr_f_5year_45_s  =  require('../sasMember/tr/Family/tr_f_5year_45_s.js');
var tr_f_5year_90_m  =  require('../sasMember/tr/Family/tr_f_5year_90_m.js');
var tr_f_5year_90_s  =  require('../sasMember/tr/Family/tr_f_5year_90_s.js');
var tr_f_5year_180_m =  require('../sasMember/tr/Family/tr_f_5year_180_m.js');
var tr_f_5year_180_s =  require('../sasMember/tr/Family/tr_f_5year_180_s.js');
var tr_f_5year_365_m =  require('../sasMember/tr/Family/tr_f_5year_365_m.js');
var tr_f_5year_365_s =  require('../sasMember/tr/Family/tr_f_5year_365_s.js');


browser.driver.manage().window().maximize();

browser.baseUrl = "http://gridstaging.globalrescue.com";

//--------------------------------Travel Memberships for individual------------------------------------
// tr_ind_1year_45_m.test();
// tr_ind_1year_45_s.test();
// tr_ind_1year_90_m.test();
// tr_ind_1year_90_s.test();
// tr_ind_1year_180_m.test();
// tr_ind_1year_180_s.test();
// tr_ind_1year_365_m.test();
// tr_ind_1year_365_s.test();
// tr_ind_2year_45_m.test();
// tr_ind_2year_45_s.test();
// tr_ind_2year_90_m.test();
// tr_ind_2year_90_s.test();
// tr_ind_2year_180_m.test();
// tr_ind_2year_180_s.test();
// tr_ind_2year_365_m.test();
// tr_ind_2year_365_s.test();
// tr_ind_3year_45_m.test();
// tr_ind_3year_45_s.test();
// tr_ind_3year_90_m.test();
// tr_ind_3year_90_s.test();
// tr_ind_3year_180_m.test();
// tr_ind_3year_180_s.test();
// tr_ind_3year_365_m.test();
// tr_ind_3year_365_s.test();
// tr_ind_4year_45_m.test();
// tr_ind_4year_45_s.test();
// tr_ind_4year_90_m.test();
// tr_ind_4year_90_s.test();
// tr_ind_4year_180_m.test();
// tr_ind_4year_180_s.test();
// tr_ind_4year_365_m.test();
// tr_ind_4year_365_s.test();
// tr_ind_5year_45_m.test();
// tr_ind_5year_45_s.test();
// tr_ind_5year_90_m.test();
// tr_ind_5year_90_s.test();
// tr_ind_5year_180_m.test();
// tr_ind_5year_180_s.test();
// tr_ind_5year_365_m.test();
// tr_ind_5year_365_s.test();


//----------------------------------Travel memberships for family --------------------------------------------

// tr_f_1year_45_m.test();
// tr_f_1year_45_s.test(); 
// tr_f_1year_90_m.test(); 
// tr_f_1year_90_s.test(); 
// tr_f_1year_180_m.test();
// tr_f_1year_45_s.test(); 
// tr_f_1year_180_s.test();
// tr_f_1year_365_m.test();
// tr_f_1year_365_s.test();
// tr_f_2year_45_m.test(); 
// tr_f_2year_45_s.test(); 
// tr_f_2year_90_m.test(); 
// tr_f_2year_90_s.test(); 
// tr_f_2year_180_m.test();
// tr_f_2year_180_s.test();
// tr_f_2year_365_m.test();
// tr_f_2year_365_s.test();
// tr_f_3year_45_m.test(); 
// tr_f_3year_45_s.test(); 
// tr_f_3year_90_m.test(); 
// tr_f_3year_90_s.test(); 
// tr_f_3year_180_m.test();
// tr_f_3year_180_s.test();
// tr_f_3year_365_m.test();
// tr_f_3year_365_s.test();
// tr_f_4year_45_m.test(); 
// tr_f_4year_45_s.test(); 
// tr_f_4year_90_m.test(); 
// tr_f_4year_90_s.test(); 
// tr_f_4year_180_m.test();
// tr_f_4year_180_s.test();
// tr_f_4year_365_m.test();
// tr_f_4year_365_s.test();
// tr_f_5year_45_m.test(); 
// tr_f_5year_45_s.test(); 
// tr_f_5year_90_m.test(); 
// tr_f_5year_90_s.test(); 
// tr_f_5year_180_m.test();
// tr_f_5year_180_s.test();
// tr_f_5year_365_m.test();
// tr_f_5year_365_s.test();

